#pragma once
#define PAPERBACK_VERSION_MAJOR 0
#define PAPERBACK_VERSION_MINOR 6
#define PAPERBACK_VERSION_PATCH 1
#define PAPERBACK_VERSION_BUILD 0
#define PAPERBACK_STRINGIFY(x) #x
#define PAPERBACK_TOSTRING(x) PAPERBACK_STRINGIFY(x)
#define PAPERBACK_VERSION_STRING PAPERBACK_TOSTRING(PAPERBACK_VERSION_MAJOR) "." PAPERBACK_TOSTRING(PAPERBACK_VERSION_MINOR) "." PAPERBACK_TOSTRING(PAPERBACK_VERSION_PATCH)
#define PAPERBACK_VERSION_STRING_FULL PAPERBACK_TOSTRING(PAPERBACK_VERSION_MAJOR) "." PAPERBACK_TOSTRING(PAPERBACK_VERSION_MINOR) "." PAPERBACK_TOSTRING(PAPERBACK_VERSION_PATCH) "." PAPERBACK_TOSTRING(PAPERBACK_VERSION_BUILD)
